### ISSUE TITLE
Which kernel works with which ROMs and which model?

### ISSUE THREAD

**Issue by min050820** [ShadySquirrel/e980-zeKrnl#1]
I ended up here to get a usable kernel for my phone, but now I have some question about its compatibility. There seems to be few branches according to its intended uses. I found some of these will be interesting.

* lp-dev-gfx
* lp-dev-v17
* lp-dev-v17-f240 (Apparently this ROM is F240 counterpart for above)
* lp-f240x_exp-gfx (This doesn't seem to have E98x counterpart. I wonder why?)

Could you please note which ROMs are intended for what use? (e.g. You said v1.8 won't work on other ROMs [on this thread](https://forum.xda-developers.com/optimus-g-pro/development/rom-slimlp-beta-0-8-t3213222). Which ROMs does it apply for?)

Note: I'm asking here because there is no other way to communicate. You have not filled E-mail field on profile, GitHub's own PM is gone a long time ago, etc.

**Comment by ShadySquirrel** [comment]
You shouldn't use any of those, since those branches are old and deprecated.

Main branch is lollipop-main and it contains all fixes/backports to gpu&mdp and other drivers (and also, it's the latest version of ShadyKernel used in last SlimLP for E98x build).

If you plan to use this for ROM builds, just revert commit: b00ffcc2a06ba280492e0b434010725538b8b5cb (squashed LMK update), because it causes issues on some devices (kills Settings or heavier apps during runtime).

You can use this kernel with other E98x ROMs, but you'll have to either replace proprietary gpu libs with mine (not recommended), or build them yourself using new proprietary libs ([link to repo](https://github.com/ShadySquirrel/proprietary_vendor_lge/tree/lollipop]), use lollipop branch) since new gpu drivers require new gpu libs.

No other modifications are necessary, but if you're building from CM repos, please revert latest changes made for LiveDisplay in device_e980 and gproj-common repos... Or if you want, use [my device tree](https://github.com/ShadySquirrel/android_device_lge_e980) (branch slim-lp-dev, just adjust to your ROM)

P.S. My mail is set as private, sorry. You can always contact me on XDA :)

**Comment by min050820** [comment]
Then is it possible to just use defconfig from one of those deprecated f240 branch and expect it to work? Or do I have to merge them?
And, does (https://github.com/ShadySquirrel/proprietary_vendor_lge/tree/lollipop)[this repo] work with f240? Sorry for asking too much. And thanks in advance.

**Comment by ShadySquirrel** [comment]
There are some config differences between 1.7 and 1.8, so I'd recommend you to just copy an original ShadyKernel_e98x_defconfig to desired one and do a quick diff (using meld or tool like that) between e98x and f240x defconfigs. 

There may be other changes to board files necessary (I remember some users with F240x having boot issues with my unpublished f240x branch, but friend who tested on his F240 had no issue, main reason I've stoped working on F240 kernel branch is that many people came with "It doesn't work", but provided no logs). Also, before you start any ROM building, I'd suggest to test kernel on your device first with pushed GPU libs (I think zip file is still available in SlimLP thread, also there is a convinient buiding script which will generate flashable for you, you'll just have to add necessary initrd files and configure paths to compiler) because not all G Pros are equal, for some reason only LG knows. From my experience, this will work flawlessly on geefhd, geefhd4g and probably some of omega boards, not sure about others.

Yes, proprietary files are universal for all G Pros, I've snatched GPU drivers from LG's F240K Lollipop firmware :)
